In [1]:
import os
import gc
import warnings

import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
data= pd.read_csv('../Downloads/파이널프로젝트_RAW_210329_210926.csv')
data.head(10)
#105419 rows X 18 columns

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,tax_free_amount,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,201435.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,NaN,NaN,110500.0,110500.0,NaN,VBANK,개발자 커리어,NaN
1,970650,432862.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,NaN,NaN,116000.0,116000.0,NaN,CARD,영상 편집,2020-12-02 0:00:00
2,970657,72297.0,204246.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,190900.0,NaN,CARD,NaN,2021-03-04 0:00:00
3,970656,72297.0,204246.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,NaN,NaN,190900.0,190900.0,NaN,CARD,NaN,2021-03-04 0:00:00
4,970658,478028.0,201797.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14 0:00:00
5,970655,478028.0,201797.0,ORDER,CANCELLED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:56,97500,NaN,NaN,117500.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14 0:00:00
6,970614,477910.0,NaN,ORDER,CANCELLED,프로모션 : 2021 내 커리어 지켜 줄 UX/UI 디자인 한끝세트 (3월 프리패스),크리에이티브,올인원,2021-03-28 15:22:36,299000,NaN,NaN,299000.0,299000.0,NaN,CARD,NaN,NaN
7,970664,460730.0,200622.0,ORDER,CANCELLED,올인원 패키지 : 기업가치 평가와 M&A 전략 실무,부동산/금융,올인원,2021-03-28 15:25:42,112500,NaN,NaN,122500.0,122500.0,NaN,CARD,금융/투자 실무,2019-05-02 0:00:00
8,970669,478033.0,203178.0,PAYMENT,COMPLETED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:26:47,96000,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,116000.0,116000.0,NaN,CARD,영상 편집,2020-12-02 0:00:00
9,970667,478033.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:26:48,96000,NaN,NaN,116000.0,116000.0,NaN,CARD,영상 편집,2020-12-02 0:00:00

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105419 entries, 0 to 105418
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      105419 non-null  int64
 1   customer_id             105416 non-null  float64
 2   course_id               100212 non-null  float64
 3   type                    105419 non-null  object
 4   state                   105419 non-null  object
 5   course_title            105403 non-null  object
 6   category_title          105395 non-null  object
 7   format                  105403 non-null  object
 8   completed_at            105419 non-null  object
 9   transaction_amount      105419 non-null  int64
 10  coupon_title            31817 non-null   object
 11  coupon_discount_amount  31817 non-null   float64
 12  sale_price              104291 non-null  float64
 13  tax_free_amount         104291 non-null  float64
 14  pg                      90344 non-null   object
 15  method                  92323 non-null   object
 16  subcategory_title       85590 non-null   object
 17  marketing_start_at      87440 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 14.5+ MB

In [4]:
data['coupon_discount_amount'] = data['sale_price'] - data['transaction_amount']#coupon_discount결측치 제거

In [7]:
data['sale_price'] = data['sale_price'].fillna(data['transaction_amount']) #sale_price 결측치 제거

In [9]:
del data['tax_free_amount']

In [11]:
data['pg'] = data['pg'].fillna('default') #NaN은 초기값이므로 default

In [12]:
data['marketing_start_at'] = data['marketing_start_at'].fillna(data['completed_at']) #날짜 없는 것은 마지막 끝 날짜로

In [13]:
#method 결측치를 위한 최빈값 구하기
data['method'].agg(**{
    'most_common_value':lambda x:x.mode()
}).reset_index()

             level_0  level_1 method
0  most_common_value        0   CARD

In [14]:

data['method'] = data['method'].fillna('CARD') #최반값 설정

In [20]:
idx = data[data['type'] == "ORDER" ].index     
data.drop(idx , inplace=True) # 해당 인덱스를 제거함

In [21]:
idx = data[data['type'] == "TRANSACTION" ].index     
data.drop(idx , inplace=True) # 해당 인덱스를 제거함

In [23]:
idx = data[data['state'] == "PENDING"].index     
data.drop(idx , inplace=True) # 해당 인덱스를 제거함

In [24]:
idx = data[data['state'] == "CANCELLED"].index     
data.drop(idx , inplace=True) # 해당 인덱스를 제거함

In [25]:
idx = data[data['state'] == "HIDDEN"].index     
data.drop(idx , inplace=True) # 해당 인덱스를 제거함

In [26]:
idx = data[data['state'] == "DELETED"].index     
data.drop(idx , inplace=True) # 해당 인덱스를 제거함

In [39]:
data[~data['coupon_title'].str.contains("검수용", na=False, case=False)]

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
2,970657,72297.0,204246.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,default,CARD,NaN,2021-03-04 0:00:00
4,970658,478028.0,201797.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,default,CARD,PPT/보고서,2019-11-14 0:00:00
8,970669,478033.0,203178.0,PAYMENT,COMPLETED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:26:47,96000,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,116000.0,default,CARD,영상 편집,2020-12-02 0:00:00
10,970671,469860.0,203644.0,PAYMENT,COMPLETED,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,올인원,2021-03-28 15:27:17,263000,NaN,0.0,263000.0,default,CARD,NaN,2020-11-27 0:00:00
14,970676,478035.0,203720.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 프론트엔드 개발,프로그래밍,올인원,2021-03-28 15:31:01,91000,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,111000.0,default,CARD,프론트엔드 개발,2021-02-02 0:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105411,1364969,669238.0,204286.0,PAYMENT,COMPLETED,초격차 패키지 : 한번에 끝내는 3D 디자인 툴,디자인,올인원,2021-09-25 13:39:26,212000,[미래투자금] 온라인 강의 2만원 할인쿠폰,20000.0,232000.0,INICIS,CARD,디자인툴,2021-04-23 0:00:00
105412,1364976,384003.0,203178.0,PAYMENT,COMPLETED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-09-25 13:46:29,149000,NaN,0.0,149000.0,KAKAO,CARD,영상 편집,2020-12-02 0:00:00
105413,1364991,670891.0,203935.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 파이썬 웹 개발,프로그래밍,올인원,2021-09-25 14:01:26,159000,[미래투자금] 온라인 강의 2만원 할인쿠폰,20000.0,179000.0,INICIS,CARD,백엔드 개발,2021-05-31 0:00:00
105416,1364996,640697.0,205365.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15 0:00:00
105418,1365007,610626.0,206720.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17 0:00:00

In [29]:
data.isnull().sum()

id                            0
customer_id                   0
course_id                  2156
type                          0
state                         0
course_title                  1
category_title                4
format                        1
completed_at                  0
transaction_amount            0
coupon_title              32975
coupon_discount_amount     1080
sale_price                    0
pg                            0
method                        0
subcategory_title         10307
marketing_start_at            0
dtype: int64

In [43]:
data[data['course_title'].isnull()]

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
47361,1117129,549990.0,NaN,PAYMENT,COMPLETED,NaN,NaN,NaN,2021-06-02 16:48:37,10500000,NaN,NaN,10500000.0,default,TRANSFER,NaN,2021-06-02 16:48:37

In [45]:
data.drop(['1117129'])

KeyError: "['1117129'] not found in axis"

In [44]:
data[data['category_title'].isnull()]

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
41878,1078156,62566.0,NaN,REFUND,COMPLETED,프로모션 : 자유이용권 (3월),NaN,온라인,2021-05-26 22:06:00,-199000,NaN,398000.0,199000.0,default,TRANSFER,NaN,2021-05-26 22:06:00
47361,1117129,549990.0,NaN,PAYMENT,COMPLETED,NaN,NaN,NaN,2021-06-02 16:48:37,10500000,NaN,NaN,10500000.0,default,TRANSFER,NaN,2021-06-02 16:48:37
72639,1212937,591404.0,NaN,PAYMENT,COMPLETED,프로모션 : 풀스택 데이터 사이언티스트를 위한 필수 iPad 패키지 (7월 현물 프...,NaN,올인원,2021-07-12 23:38:42,990000,NaN,0.0,990000.0,INICIS,CARD,NaN,2021-07-12 23:38:42
74975,1223480,598011.0,NaN,PAYMENT,COMPLETED,프로모션 : 풀스택 데이터 사이언티스트를 위한 필수 iPad 패키지 (7월 현물 프...,NaN,올인원,2021-07-18 12:31:01,990000,NaN,0.0,990000.0,INICIS,CARD,NaN,2021-07-18 12:31:01